/* Generated by Yosys 0.66+115 (git sha1 5d7486115, Release, GNU /opt/rh/gcc-toolset-13/root/usr/bin/g++ 13.3.1) */

(* dynports =  1  *)
(* top =  1  *)
(* src = "afifo.v:2.1-90.15" *)
module afifo(wclk, wrstn, wren, wdata, wfull, rclk, rrstn, rden, rdata, rempty);
  (* src = "afifo.v:6.17-6.21" *)
  input wclk;
  wire wclk;
  (* src = "afifo.v:6.22-6.27" *)
  input wrstn;
  wire wrstn;
  (* src = "afifo.v:6.28-6.32" *)
  input wren;
  wire wren;
  (* src = "afifo.v:7.26-7.31" *)
  input [7:0] wdata;
  wire [7:0] wdata;
  (* init = 1'h0 *)
  (* src = "afifo.v:8.17-8.22" *)
  output wfull;
  wire wfull;
  (* src = "afifo.v:11.17-11.21" *)
  input rclk;
  wire rclk;
  (* src = "afifo.v:11.22-11.27" *)
  input rrstn;
  wire rrstn;
  (* src = "afifo.v:11.28-11.32" *)
  input rden;
  wire rden;
  (* src = "afifo.v:12.27-12.32" *)
  output [7:0] rdata;
  wire [7:0] rdata;
  (* init = 1'h1 *)
  (* src = "afifo.v:13.17-13.23" *)
  output rempty;
  wire rempty;
  wire _000_;
  wire _001_;
  wire _002_;
  wire _003_;
  wire _004_;
  wire _005_;
  wire _006_;
  wire _007_;
  wire _008_;
  wire _009_;
  wire _010_;
  wire _011_;
  wire _012_;
  wire _013_;
  wire _014_;
  wire _015_;
  wire _016_;
  wire _017_;
  wire _018_;
  wire _019_;
  wire _020_;
  wire _021_;
  wire _022_;
  wire _023_;
  wire _024_;
  wire _025_;
  wire _026_;
  wire _027_;
  wire _028_;
  wire _029_;
  wire _030_;
  wire _031_;
  wire _032_;
  wire _033_;
  wire _034_;
  wire _035_;
  wire _036_;
  wire _037_;
  wire _038_;
  wire _039_;
  wire _040_;
  wire _041_;
  wire _042_;
  wire _043_;
  wire _044_;
  wire _045_;
  wire _046_;
  wire _047_;
  wire _048_;
  wire _049_;
  wire _050_;
  wire _051_;
  wire _052_;
  wire _053_;
  wire _054_;
  wire _055_;
  wire _056_;
  wire _057_;
  wire _058_;
  wire _059_;
  wire _060_;
  wire _061_;
  wire _062_;
  wire _063_;
  wire _064_;
  wire _065_;
  wire _066_;
  wire _067_;
  wire _068_;
  wire _069_;
  wire _070_;
  wire _071_;
  wire _072_;
  wire _073_;
  wire _074_;
  wire _075_;
  wire _076_;
  wire _077_;
  wire _078_;
  wire _079_;
  wire _080_;
  wire _081_;
  wire _082_;
  wire _083_;
  wire _084_;
  wire _085_;
  wire _086_;
  wire _087_;
  wire _088_;
  wire _089_;
  wire _090_;
  wire [7:0] \mem[0] ;
  wire [7:0] \mem[10] ;
  wire [7:0] \mem[11] ;
  wire [7:0] \mem[12] ;
  wire [7:0] \mem[13] ;
  wire [7:0] \mem[14] ;
  wire [7:0] \mem[15] ;
  wire [7:0] \mem[1] ;
  wire [7:0] \mem[2] ;
  wire [7:0] \mem[3] ;
  wire [7:0] \mem[4] ;
  wire [7:0] \mem[5] ;
  wire [7:0] \mem[6] ;
  wire [7:0] \mem[7] ;
  wire [7:0] \mem[8] ;
  wire [7:0] \mem[9] ;
  (* src = "afifo.v:15.26-15.31" *)
  wire [3:0] raddr;
  (* init = 5'h00 *)
  (* src = "afifo.v:17.54-17.58" *)
  wire [4:0] rbin;
  (* src = "afifo.v:20.28-20.36" *)
  wire [4:0] rbinnext;
  (* src = "afifo.v:16.22-16.33" *)
  wire rempty_next;
  (* init = 5'hx0 *)
  (* src = "afifo.v:17.48-17.53" *)
  wire [4:0] rgray;
  (* src = "afifo.v:20.18-20.27" *)
  wire [4:0] rgraynext;
  (* init = 5'h00 *)
  (* src = "afifo.v:17.69-17.78" *)
  wire [4:0] rq1_wgray;
  (* init = 5'h00 *)
  (* src = "afifo.v:17.59-17.68" *)
  wire [4:0] rq2_wgray;
  (* src = "afifo.v:15.20-15.25" *)
  wire [3:0] waddr;
  (* init = 5'hx0 *)
  (* src = "afifo.v:17.17-17.21" *)
  wire [4:0] wbin;
  (* src = "afifo.v:19.27-19.35" *)
  wire [4:0] wbinnext;
  (* src = "afifo.v:16.11-16.21" *)
  wire wfull_next;
  (* init = 5'h00 *)
  (* src = "afifo.v:17.22-17.27" *)
  wire [4:0] wgray;
  (* src = "afifo.v:19.17-19.26" *)
  wire [4:0] wgraynext;
  (* init = 5'h00 *)
  (* src = "afifo.v:17.38-17.47" *)
  wire [4:0] wq1_rgray;
  (* init = 5'h00 *)
  (* src = "afifo.v:17.28-17.37" *)
  wire [4:0] wq2_rgray;
  sky130_fd_sc_hd__clkinv_1 _091_ (
    .A(wbin[2]),
    .Y(_016_)
  );
  sky130_fd_sc_hd__clkinv_1 _092_ (
    .A(rempty),
    .Y(_017_)
  );
  sky130_fd_sc_hd__clkinv_1 _093_ (
    .A(rbin[1]),
    .Y(_018_)
  );
  sky130_fd_sc_hd__nand2b_1 _094_ (
    .A_N(wfull),
    .B(wren),
    .Y(_019_)
  );
  sky130_fd_sc_hd__nand3b_1 _095_ (
    .A_N(wfull),
    .B(wbin[0]),
    .C(wren),
    .Y(_020_)
  );
  sky130_fd_sc_hd__nand4b_1 _096_ (
    .A_N(wfull),
    .B(wbin[0]),
    .C(wbin[1]),
    .D(wren),
    .Y(_021_)
  );
  sky130_fd_sc_hd__nand2_1 _097_ (
    .A(_016_),
    .B(_021_),
    .Y(_022_)
  );
  sky130_fd_sc_hd__xnor2_1 _098_ (
    .A(wbin[2]),
    .B(_021_),
    .Y(wbinnext[2])
  );
  sky130_fd_sc_hd__lpflow_inputiso1p_1 _099_ (
    .A(wbin[1]),
    .SLEEP(_020_),
    .X(_023_)
  );
  sky130_fd_sc_hd__xor2_1 _100_ (
    .A(wbin[1]),
    .B(_020_),
    .X(_024_)
  );
  sky130_fd_sc_hd__clkinv_1 _101_ (
    .A(_024_),
    .Y(wbinnext[1])
  );
  sky130_fd_sc_hd__and3b_1 _102_ (
    .A_N(rempty),
    .B(rbin[0]),
    .C(rden),
    .X(_025_)
  );
  sky130_fd_sc_hd__a21oi_1 _103_ (
    .A1(rden),
    .A2(_017_),
    .B1(rbin[0]),
    .Y(_026_)
  );
  sky130_fd_sc_hd__nor2_1 _104_ (
    .A(_025_),
    .B(_026_),
    .Y(rbinnext[0])
  );
  sky130_fd_sc_hd__mux4_2 _105_ (
    .A0(\mem[4] [6]),
    .A1(\mem[5] [6]),
    .A2(\mem[6] [6]),
    .A3(\mem[7] [6]),
    .S0(rbin[0]),
    .S1(rbin[1]),
    .X(_027_)
  );
  sky130_fd_sc_hd__mux4_2 _106_ (
    .A0(\mem[0] [6]),
    .A1(\mem[1] [6]),
    .A2(\mem[2] [6]),
    .A3(\mem[3] [6]),
    .S0(rbin[0]),
    .S1(rbin[1]),
    .X(_028_)
  );
  sky130_fd_sc_hd__mux4_2 _107_ (
    .A0(\mem[12] [6]),
    .A1(\mem[13] [6]),
    .A2(\mem[14] [6]),
    .A3(\mem[15] [6]),
    .S0(rbin[0]),
    .S1(rbin[1]),
    .X(_029_)
  );
  sky130_fd_sc_hd__mux4_2 _108_ (
    .A0(\mem[8] [6]),
    .A1(\mem[9] [6]),
    .A2(\mem[10] [6]),
    .A3(\mem[11] [6]),
    .S0(rbin[0]),
    .S1(rbin[1]),
    .X(_030_)
  );
  sky130_fd_sc_hd__mux4_2 _109_ (
    .A0(_028_),
    .A1(_030_),
    .A2(_027_),
    .A3(_029_),
    .S0(rbin[3]),
    .S1(rbin[2]),
    .X(rdata[6])
  );
  sky130_fd_sc_hd__mux4_2 _110_ (
    .A0(\mem[4] [5]),
    .A1(\mem[5] [5]),
    .A2(\mem[6] [5]),
    .A3(\mem[7] [5]),
    .S0(rbin[0]),
    .S1(rbin[1]),
    .X(_031_)
  );
  sky130_fd_sc_hd__mux4_2 _111_ (
    .A0(\mem[0] [5]),
    .A1(\mem[1] [5]),
    .A2(\mem[2] [5]),
    .A3(\mem[3] [5]),
    .S0(rbin[0]),
    .S1(rbin[1]),
    .X(_032_)
  );
  sky130_fd_sc_hd__mux2i_1 _112_ (
    .A0(_032_),
    .A1(_031_),
    .S(rbin[2]),
    .Y(_033_)
  );
  sky130_fd_sc_hd__mux4_2 _113_ (
    .A0(\mem[10] [5]),
    .A1(\mem[14] [5]),
    .A2(\mem[11] [5]),
    .A3(\mem[15] [5]),
    .S0(rbin[2]),
    .S1(rbin[0]),
    .X(_034_)
  );
  sky130_fd_sc_hd__lpflow_inputiso1p_1 _114_ (
    .A(_018_),
    .SLEEP(_034_),
    .X(_035_)
  );
  sky130_fd_sc_hd__mux4_2 _115_ (
    .A0(\mem[8] [5]),
    .A1(\mem[12] [5]),
    .A2(\mem[9] [5]),
    .A3(\mem[13] [5]),
    .S0(rbin[2]),
    .S1(rbin[0]),
    .X(_036_)
  );
  sky130_fd_sc_hd__o211ai_1 _116_ (
    .A1(rbin[1]),
    .A2(_036_),
    .B1(_035_),
    .C1(rbin[3]),
    .Y(_037_)
  );
  sky130_fd_sc_hd__o21ai_0 _117_ (
    .A1(rbin[3]),
    .A2(_033_),
    .B1(_037_),
    .Y(rdata[5])
  );
  sky130_fd_sc_hd__mux4_2 _118_ (
    .A0(\mem[4] [4]),
    .A1(\mem[5] [4]),
    .A2(\mem[6] [4]),
    .A3(\mem[7] [4]),
    .S0(rbin[0]),
    .S1(rbin[1]),
    .X(_038_)
  );
  sky130_fd_sc_hd__mux4_2 _119_ (
    .A0(\mem[0] [4]),
    .A1(\mem[1] [4]),
    .A2(\mem[2] [4]),
    .A3(\mem[3] [4]),
    .S0(rbin[0]),
    .S1(rbin[1]),
    .X(_039_)
  );
  sky130_fd_sc_hd__mux4_2 _120_ (
    .A0(\mem[12] [4]),
    .A1(\mem[13] [4]),
    .A2(\mem[14] [4]),
    .A3(\mem[15] [4]),
    .S0(rbin[0]),
    .S1(rbin[1]),
    .X(_040_)
  );
  sky130_fd_sc_hd__mux4_2 _121_ (
    .A0(\mem[8] [4]),
    .A1(\mem[9] [4]),
    .A2(\mem[10] [4]),
    .A3(\mem[11] [4]),
    .S0(rbin[0]),
    .S1(rbin[1]),
    .X(_041_)
  );
  sky130_fd_sc_hd__mux4_2 _122_ (
    .A0(_039_),
    .A1(_041_),
    .A2(_038_),
    .A3(_040_),
    .S0(rbin[3]),
    .S1(rbin[2]),
    .X(rdata[4])
  );
  sky130_fd_sc_hd__mux4_2 _123_ (
    .A0(\mem[4] [3]),
    .A1(\mem[5] [3]),
    .A2(\mem[6] [3]),
    .A3(\mem[7] [3]),
    .S0(rbin[0]),
    .S1(rbin[1]),
    .X(_042_)
  );
  sky130_fd_sc_hd__mux4_2 _124_ (
    .A0(\mem[0] [3]),
    .A1(\mem[1] [3]),
    .A2(\mem[2] [3]),
    .A3(\mem[3] [3]),
    .S0(rbin[0]),
    .S1(rbin[1]),
    .X(_043_)
  );
  sky130_fd_sc_hd__mux2i_1 _125_ (
    .A0(_043_),
    .A1(_042_),
    .S(rbin[2]),
    .Y(_044_)
  );
  sky130_fd_sc_hd__mux4_2 _126_ (
    .A0(\mem[10] [3]),
    .A1(\mem[14] [3]),
    .A2(\mem[11] [3]),
    .A3(\mem[15] [3]),
    .S0(rbin[2]),
    .S1(rbin[0]),
    .X(_045_)
  );
  sky130_fd_sc_hd__mux4_2 _127_ (
    .A0(\mem[8] [3]),
    .A1(\mem[12] [3]),
    .A2(\mem[9] [3]),
    .A3(\mem[13] [3]),
    .S0(rbin[2]),
    .S1(rbin[0]),
    .X(_046_)
  );
  sky130_fd_sc_hd__nor2_1 _128_ (
    .A(rbin[1]),
    .B(_046_),
    .Y(_047_)
  );
  sky130_fd_sc_hd__o21ai_0 _129_ (
    .A1(_018_),
    .A2(_045_),
    .B1(rbin[3]),
    .Y(_048_)
  );
  sky130_fd_sc_hd__o22ai_1 _130_ (
    .A1(rbin[3]),
    .A2(_044_),
    .B1(_047_),
    .B2(_048_),
    .Y(rdata[3])
  );
  sky130_fd_sc_hd__mux4_2 _131_ (
    .A0(\mem[4] [2]),
    .A1(\mem[5] [2]),
    .A2(\mem[6] [2]),
    .A3(\mem[7] [2]),
    .S0(rbin[0]),
    .S1(rbin[1]),
    .X(_049_)
  );
  sky130_fd_sc_hd__mux4_2 _132_ (
    .A0(\mem[0] [2]),
    .A1(\mem[1] [2]),
    .A2(\mem[2] [2]),
    .A3(\mem[3] [2]),
    .S0(rbin[0]),
    .S1(rbin[1]),
    .X(_050_)
  );
  sky130_fd_sc_hd__mux4_2 _133_ (
    .A0(\mem[12] [2]),
    .A1(\mem[13] [2]),
    .A2(\mem[14] [2]),
    .A3(\mem[15] [2]),
    .S0(rbin[0]),
    .S1(rbin[1]),
    .X(_051_)
  );
  sky130_fd_sc_hd__mux4_2 _134_ (
    .A0(\mem[8] [2]),
    .A1(\mem[9] [2]),
    .A2(\mem[10] [2]),
    .A3(\mem[11] [2]),
    .S0(rbin[0]),
    .S1(rbin[1]),
    .X(_052_)
  );
  sky130_fd_sc_hd__mux4_2 _135_ (
    .A0(_050_),
    .A1(_052_),
    .A2(_049_),
    .A3(_051_),
    .S0(rbin[3]),
    .S1(rbin[2]),
    .X(rdata[2])
  );
  sky130_fd_sc_hd__mux4_2 _136_ (
    .A0(\mem[4] [1]),
    .A1(\mem[5] [1]),
    .A2(\mem[6] [1]),
    .A3(\mem[7] [1]),
    .S0(rbin[0]),
    .S1(rbin[1]),
    .X(_053_)
  );
  sky130_fd_sc_hd__mux4_2 _137_ (
    .A0(\mem[0] [1]),
    .A1(\mem[1] [1]),
    .A2(\mem[2] [1]),
    .A3(\mem[3] [1]),
    .S0(rbin[0]),
    .S1(rbin[1]),
    .X(_054_)
  );
  sky130_fd_sc_hd__mux4_2 _138_ (
    .A0(\mem[12] [1]),
    .A1(\mem[13] [1]),
    .A2(\mem[14] [1]),
    .A3(\mem[15] [1]),
    .S0(rbin[0]),
    .S1(rbin[1]),
    .X(_055_)
  );
  sky130_fd_sc_hd__mux4_2 _139_ (
    .A0(\mem[8] [1]),
    .A1(\mem[9] [1]),
    .A2(\mem[10] [1]),
    .A3(\mem[11] [1]),
    .S0(rbin[0]),
    .S1(rbin[1]),
    .X(_056_)
  );
  sky130_fd_sc_hd__mux4_2 _140_ (
    .A0(_054_),
    .A1(_056_),
    .A2(_053_),
    .A3(_055_),
    .S0(rbin[3]),
    .S1(rbin[2]),
    .X(rdata[1])
  );
  sky130_fd_sc_hd__mux4_2 _141_ (
    .A0(\mem[8] [0]),
    .A1(\mem[12] [0]),
    .A2(\mem[9] [0]),
    .A3(\mem[13] [0]),
    .S0(rbin[2]),
    .S1(rbin[0]),
    .X(_057_)
  );
  sky130_fd_sc_hd__mux4_2 _142_ (
    .A0(\mem[0] [0]),
    .A1(\mem[4] [0]),
    .A2(\mem[1] [0]),
    .A3(\mem[5] [0]),
    .S0(rbin[2]),
    .S1(rbin[0]),
    .X(_058_)
  );
  sky130_fd_sc_hd__mux4_2 _143_ (
    .A0(\mem[10] [0]),
    .A1(\mem[14] [0]),
    .A2(\mem[11] [0]),
    .A3(\mem[15] [0]),
    .S0(rbin[2]),
    .S1(rbin[0]),
    .X(_059_)
  );
  sky130_fd_sc_hd__mux4_2 _144_ (
    .A0(\mem[2] [0]),
    .A1(\mem[6] [0]),
    .A2(\mem[3] [0]),
    .A3(\mem[7] [0]),
    .S0(rbin[2]),
    .S1(rbin[0]),
    .X(_060_)
  );
  sky130_fd_sc_hd__mux4_2 _145_ (
    .A0(_058_),
    .A1(_060_),
    .A2(_057_),
    .A3(_059_),
    .S0(rbin[1]),
    .S1(rbin[3]),
    .X(rdata[0])
  );
  sky130_fd_sc_hd__and4b_1 _146_ (
    .A_N(rempty),
    .B(rbin[0]),
    .C(rbin[1]),
    .D(rden),
    .X(_061_)
  );
  sky130_fd_sc_hd__and2_0 _147_ (
    .A(rbin[2]),
    .B(_061_),
    .X(_062_)
  );
  sky130_fd_sc_hd__nor2_1 _148_ (
    .A(rbin[3]),
    .B(_062_),
    .Y(_063_)
  );
  sky130_fd_sc_hd__xnor2_1 _149_ (
    .A(rbin[4]),
    .B(_063_),
    .Y(rgraynext[3])
  );
  sky130_fd_sc_hd__nor2_1 _150_ (
    .A(rbin[2]),
    .B(_061_),
    .Y(_064_)
  );
  sky130_fd_sc_hd__xnor2_1 _151_ (
    .A(rbin[3]),
    .B(_064_),
    .Y(rgraynext[2])
  );
  sky130_fd_sc_hd__nor2_1 _152_ (
    .A(rbin[1]),
    .B(_025_),
    .Y(_065_)
  );
  sky130_fd_sc_hd__xnor2_1 _153_ (
    .A(rbin[2]),
    .B(_065_),
    .Y(rgraynext[1])
  );
  sky130_fd_sc_hd__xnor2_1 _154_ (
    .A(rbin[1]),
    .B(_026_),
    .Y(rgraynext[0])
  );
  sky130_fd_sc_hd__nand2_1 _155_ (
    .A(rbin[3]),
    .B(_062_),
    .Y(_066_)
  );
  sky130_fd_sc_hd__xnor2_1 _156_ (
    .A(rbin[4]),
    .B(_066_),
    .Y(rbinnext[4])
  );
  sky130_fd_sc_hd__nand2b_1 _157_ (
    .A_N(wbin[3]),
    .B(wbin[2]),
    .Y(_067_)
  );
  sky130_fd_sc_hd__nor2_1 _158_ (
    .A(_021_),
    .B(_067_),
    .Y(_013_)
  );
  sky130_fd_sc_hd__o21a_1 _159_ (
    .A1(_016_),
    .A2(_021_),
    .B1(wbin[3]),
    .X(_068_)
  );
  sky130_fd_sc_hd__lpflow_inputiso1p_1 _160_ (
    .A(_013_),
    .SLEEP(_068_),
    .X(wbinnext[3])
  );
  sky130_fd_sc_hd__nand2_1 _161_ (
    .A(wbin[2]),
    .B(wbin[3]),
    .Y(_069_)
  );
  sky130_fd_sc_hd__nor2_1 _162_ (
    .A(_021_),
    .B(_069_),
    .Y(_006_)
  );
  sky130_fd_sc_hd__xnor2_1 _163_ (
    .A(wgray[4]),
    .B(_006_),
    .Y(_070_)
  );
  sky130_fd_sc_hd__clkinv_1 _164_ (
    .A(_070_),
    .Y(wbinnext[4])
  );
  sky130_fd_sc_hd__mux2i_1 _165_ (
    .A0(_070_),
    .A1(wgray[4]),
    .S(wbinnext[3]),
    .Y(wgraynext[3])
  );
  sky130_fd_sc_hd__xor2_1 _166_ (
    .A(wbin[3]),
    .B(_022_),
    .X(wgraynext[2])
  );
  sky130_fd_sc_hd__mux2_1 _167_ (
    .A0(_016_),
    .A1(wbinnext[2]),
    .S(_024_),
    .X(wgraynext[1])
  );
  sky130_fd_sc_hd__xnor2_1 _168_ (
    .A(wbin[0]),
    .B(_019_),
    .Y(wbinnext[0])
  );
  sky130_fd_sc_hd__mux2i_1 _169_ (
    .A0(_024_),
    .A1(wbin[1]),
    .S(wbinnext[0]),
    .Y(wgraynext[0])
  );
  sky130_fd_sc_hd__nor2_1 _170_ (
    .A(_062_),
    .B(_064_),
    .Y(rbinnext[2])
  );
  sky130_fd_sc_hd__nor2_1 _171_ (
    .A(_061_),
    .B(_065_),
    .Y(rbinnext[1])
  );
  sky130_fd_sc_hd__nor2b_1 _172_ (
    .A(_063_),
    .B_N(_066_),
    .Y(rbinnext[3])
  );
  sky130_fd_sc_hd__nand2_1 _173_ (
    .A(_016_),
    .B(wbin[3]),
    .Y(_071_)
  );
  sky130_fd_sc_hd__nor2_1 _174_ (
    .A(wbin[0]),
    .B(_019_),
    .Y(_072_)
  );
  sky130_fd_sc_hd__or3_1 _175_ (
    .A(wbin[0]),
    .B(wbin[1]),
    .C(_019_),
    .X(_073_)
  );
  sky130_fd_sc_hd__nor2_1 _176_ (
    .A(_071_),
    .B(_073_),
    .Y(_014_)
  );
  sky130_fd_sc_hd__nand2_1 _177_ (
    .A(wbin[1]),
    .B(_072_),
    .Y(_074_)
  );
  sky130_fd_sc_hd__nor2_1 _178_ (
    .A(_067_),
    .B(_074_),
    .Y(_012_)
  );
  sky130_fd_sc_hd__nor2_1 _179_ (
    .A(_069_),
    .B(_073_),
    .Y(_003_)
  );
  sky130_fd_sc_hd__nor2_1 _180_ (
    .A(_023_),
    .B(_067_),
    .Y(_011_)
  );
  sky130_fd_sc_hd__nor2_1 _181_ (
    .A(_071_),
    .B(_074_),
    .Y(_001_)
  );
  sky130_fd_sc_hd__nor2_1 _182_ (
    .A(_067_),
    .B(_073_),
    .Y(_010_)
  );
  sky130_fd_sc_hd__nor3_1 _183_ (
    .A(wbin[2]),
    .B(wbin[3]),
    .C(_021_),
    .Y(_009_)
  );
  sky130_fd_sc_hd__nor2_1 _184_ (
    .A(_023_),
    .B(_069_),
    .Y(_004_)
  );
  sky130_fd_sc_hd__nor3_1 _185_ (
    .A(wbin[2]),
    .B(wbin[3]),
    .C(_074_),
    .Y(_008_)
  );
  sky130_fd_sc_hd__nor2_1 _186_ (
    .A(_021_),
    .B(_071_),
    .Y(_002_)
  );
  sky130_fd_sc_hd__nor3_1 _187_ (
    .A(wbin[2]),
    .B(wbin[3]),
    .C(_023_),
    .Y(_007_)
  );
  sky130_fd_sc_hd__nor2_1 _188_ (
    .A(_069_),
    .B(_074_),
    .Y(_005_)
  );
  sky130_fd_sc_hd__nor3_1 _189_ (
    .A(wbin[2]),
    .B(wbin[3]),
    .C(_073_),
    .Y(_000_)
  );
  sky130_fd_sc_hd__mux4_2 _190_ (
    .A0(\mem[1] [7]),
    .A1(\mem[5] [7]),
    .A2(\mem[3] [7]),
    .A3(\mem[7] [7]),
    .S0(rbin[2]),
    .S1(rbin[1]),
    .X(_075_)
  );
  sky130_fd_sc_hd__mux4_2 _191_ (
    .A0(\mem[0] [7]),
    .A1(\mem[4] [7]),
    .A2(\mem[2] [7]),
    .A3(\mem[6] [7]),
    .S0(rbin[2]),
    .S1(rbin[1]),
    .X(_076_)
  );
  sky130_fd_sc_hd__mux4_2 _192_ (
    .A0(\mem[9] [7]),
    .A1(\mem[13] [7]),
    .A2(\mem[11] [7]),
    .A3(\mem[15] [7]),
    .S0(rbin[2]),
    .S1(rbin[1]),
    .X(_077_)
  );
  sky130_fd_sc_hd__mux4_2 _193_ (
    .A0(\mem[8] [7]),
    .A1(\mem[12] [7]),
    .A2(\mem[10] [7]),
    .A3(\mem[14] [7]),
    .S0(rbin[2]),
    .S1(rbin[1]),
    .X(_078_)
  );
  sky130_fd_sc_hd__mux4_2 _194_ (
    .A0(_076_),
    .A1(_078_),
    .A2(_075_),
    .A3(_077_),
    .S0(rbin[3]),
    .S1(rbin[0]),
    .X(rdata[7])
  );
  sky130_fd_sc_hd__nor2_1 _195_ (
    .A(_023_),
    .B(_071_),
    .Y(_015_)
  );
  sky130_fd_sc_hd__xnor2_1 _196_ (
    .A(rq2_wgray[2]),
    .B(rgraynext[2]),
    .Y(_079_)
  );
  sky130_fd_sc_hd__xnor2_1 _197_ (
    .A(rq2_wgray[0]),
    .B(rgraynext[0]),
    .Y(_080_)
  );
  sky130_fd_sc_hd__xnor2_1 _198_ (
    .A(rq2_wgray[1]),
    .B(rgraynext[1]),
    .Y(_081_)
  );
  sky130_fd_sc_hd__nand3_1 _199_ (
    .A(_079_),
    .B(_080_),
    .C(_081_),
    .Y(_082_)
  );
  sky130_fd_sc_hd__xor2_1 _200_ (
    .A(rq2_wgray[4]),
    .B(rbinnext[4]),
    .X(_083_)
  );
  sky130_fd_sc_hd__xor2_1 _201_ (
    .A(rq2_wgray[3]),
    .B(rgraynext[3]),
    .X(_084_)
  );
  sky130_fd_sc_hd__nor3_1 _202_ (
    .A(_082_),
    .B(_083_),
    .C(_084_),
    .Y(rempty_next)
  );
  sky130_fd_sc_hd__xnor2_1 _203_ (
    .A(wq2_rgray[3]),
    .B(wgraynext[3]),
    .Y(_085_)
  );
  sky130_fd_sc_hd__xor2_1 _204_ (
    .A(wq2_rgray[2]),
    .B(wgraynext[2]),
    .X(_086_)
  );
  sky130_fd_sc_hd__xnor2_1 _205_ (
    .A(wq2_rgray[0]),
    .B(wgraynext[0]),
    .Y(_087_)
  );
  sky130_fd_sc_hd__xnor2_1 _206_ (
    .A(wq2_rgray[1]),
    .B(wgraynext[1]),
    .Y(_088_)
  );
  sky130_fd_sc_hd__xnor2_1 _207_ (
    .A(wq2_rgray[4]),
    .B(_070_),
    .Y(_089_)
  );
  sky130_fd_sc_hd__nand3_1 _208_ (
    .A(_087_),
    .B(_088_),
    .C(_089_),
    .Y(_090_)
  );
  sky130_fd_sc_hd__nor3_1 _209_ (
    .A(_085_),
    .B(_086_),
    .C(_090_),
    .Y(wfull_next)
  );
  sky130_fd_sc_hd__edfxtp_1 _210_ (
    .CLK(wclk),
    .D(wdata[0]),
    .DE(_006_),
    .Q(\mem[15] [0])
  );
  sky130_fd_sc_hd__edfxtp_1 _211_ (
    .CLK(wclk),
    .D(wdata[1]),
    .DE(_006_),
    .Q(\mem[15] [1])
  );
  sky130_fd_sc_hd__edfxtp_1 _212_ (
    .CLK(wclk),
    .D(wdata[2]),
    .DE(_006_),
    .Q(\mem[15] [2])
  );
  sky130_fd_sc_hd__edfxtp_1 _213_ (
    .CLK(wclk),
    .D(wdata[3]),
    .DE(_006_),
    .Q(\mem[15] [3])
  );
  sky130_fd_sc_hd__edfxtp_1 _214_ (
    .CLK(wclk),
    .D(wdata[4]),
    .DE(_006_),
    .Q(\mem[15] [4])
  );
  sky130_fd_sc_hd__edfxtp_1 _215_ (
    .CLK(wclk),
    .D(wdata[5]),
    .DE(_006_),
    .Q(\mem[15] [5])
  );
  sky130_fd_sc_hd__edfxtp_1 _216_ (
    .CLK(wclk),
    .D(wdata[6]),
    .DE(_006_),
    .Q(\mem[15] [6])
  );
  sky130_fd_sc_hd__edfxtp_1 _217_ (
    .CLK(wclk),
    .D(wdata[7]),
    .DE(_006_),
    .Q(\mem[15] [7])
  );
  sky130_fd_sc_hd__edfxtp_1 _218_ (
    .CLK(wclk),
    .D(wdata[0]),
    .DE(_005_),
    .Q(\mem[14] [0])
  );
  sky130_fd_sc_hd__edfxtp_1 _219_ (
    .CLK(wclk),
    .D(wdata[1]),
    .DE(_005_),
    .Q(\mem[14] [1])
  );
  sky130_fd_sc_hd__edfxtp_1 _220_ (
    .CLK(wclk),
    .D(wdata[2]),
    .DE(_005_),
    .Q(\mem[14] [2])
  );
  sky130_fd_sc_hd__edfxtp_1 _221_ (
    .CLK(wclk),
    .D(wdata[3]),
    .DE(_005_),
    .Q(\mem[14] [3])
  );
  sky130_fd_sc_hd__edfxtp_1 _222_ (
    .CLK(wclk),
    .D(wdata[4]),
    .DE(_005_),
    .Q(\mem[14] [4])
  );
  sky130_fd_sc_hd__edfxtp_1 _223_ (
    .CLK(wclk),
    .D(wdata[5]),
    .DE(_005_),
    .Q(\mem[14] [5])
  );
  sky130_fd_sc_hd__edfxtp_1 _224_ (
    .CLK(wclk),
    .D(wdata[6]),
    .DE(_005_),
    .Q(\mem[14] [6])
  );
  sky130_fd_sc_hd__edfxtp_1 _225_ (
    .CLK(wclk),
    .D(wdata[7]),
    .DE(_005_),
    .Q(\mem[14] [7])
  );
  sky130_fd_sc_hd__edfxtp_1 _226_ (
    .CLK(wclk),
    .D(wdata[0]),
    .DE(_004_),
    .Q(\mem[13] [0])
  );
  sky130_fd_sc_hd__edfxtp_1 _227_ (
    .CLK(wclk),
    .D(wdata[1]),
    .DE(_004_),
    .Q(\mem[13] [1])
  );
  sky130_fd_sc_hd__edfxtp_1 _228_ (
    .CLK(wclk),
    .D(wdata[2]),
    .DE(_004_),
    .Q(\mem[13] [2])
  );
  sky130_fd_sc_hd__edfxtp_1 _229_ (
    .CLK(wclk),
    .D(wdata[3]),
    .DE(_004_),
    .Q(\mem[13] [3])
  );
  sky130_fd_sc_hd__edfxtp_1 _230_ (
    .CLK(wclk),
    .D(wdata[4]),
    .DE(_004_),
    .Q(\mem[13] [4])
  );
  sky130_fd_sc_hd__edfxtp_1 _231_ (
    .CLK(wclk),
    .D(wdata[5]),
    .DE(_004_),
    .Q(\mem[13] [5])
  );
  sky130_fd_sc_hd__edfxtp_1 _232_ (
    .CLK(wclk),
    .D(wdata[6]),
    .DE(_004_),
    .Q(\mem[13] [6])
  );
  sky130_fd_sc_hd__edfxtp_1 _233_ (
    .CLK(wclk),
    .D(wdata[7]),
    .DE(_004_),
    .Q(\mem[13] [7])
  );
  sky130_fd_sc_hd__edfxtp_1 _234_ (
    .CLK(wclk),
    .D(wdata[0]),
    .DE(_003_),
    .Q(\mem[12] [0])
  );
  sky130_fd_sc_hd__edfxtp_1 _235_ (
    .CLK(wclk),
    .D(wdata[1]),
    .DE(_003_),
    .Q(\mem[12] [1])
  );
  sky130_fd_sc_hd__edfxtp_1 _236_ (
    .CLK(wclk),
    .D(wdata[2]),
    .DE(_003_),
    .Q(\mem[12] [2])
  );
  sky130_fd_sc_hd__edfxtp_1 _237_ (
    .CLK(wclk),
    .D(wdata[3]),
    .DE(_003_),
    .Q(\mem[12] [3])
  );
  sky130_fd_sc_hd__edfxtp_1 _238_ (
    .CLK(wclk),
    .D(wdata[4]),
    .DE(_003_),
    .Q(\mem[12] [4])
  );
  sky130_fd_sc_hd__edfxtp_1 _239_ (
    .CLK(wclk),
    .D(wdata[5]),
    .DE(_003_),
    .Q(\mem[12] [5])
  );
  sky130_fd_sc_hd__edfxtp_1 _240_ (
    .CLK(wclk),
    .D(wdata[6]),
    .DE(_003_),
    .Q(\mem[12] [6])
  );
  sky130_fd_sc_hd__edfxtp_1 _241_ (
    .CLK(wclk),
    .D(wdata[7]),
    .DE(_003_),
    .Q(\mem[12] [7])
  );
  sky130_fd_sc_hd__edfxtp_1 _242_ (
    .CLK(wclk),
    .D(wdata[0]),
    .DE(_002_),
    .Q(\mem[11] [0])
  );
  sky130_fd_sc_hd__edfxtp_1 _243_ (
    .CLK(wclk),
    .D(wdata[1]),
    .DE(_002_),
    .Q(\mem[11] [1])
  );
  sky130_fd_sc_hd__edfxtp_1 _244_ (
    .CLK(wclk),
    .D(wdata[2]),
    .DE(_002_),
    .Q(\mem[11] [2])
  );
  sky130_fd_sc_hd__edfxtp_1 _245_ (
    .CLK(wclk),
    .D(wdata[3]),
    .DE(_002_),
    .Q(\mem[11] [3])
  );
  sky130_fd_sc_hd__edfxtp_1 _246_ (
    .CLK(wclk),
    .D(wdata[4]),
    .DE(_002_),
    .Q(\mem[11] [4])
  );
  sky130_fd_sc_hd__edfxtp_1 _247_ (
    .CLK(wclk),
    .D(wdata[5]),
    .DE(_002_),
    .Q(\mem[11] [5])
  );
  sky130_fd_sc_hd__edfxtp_1 _248_ (
    .CLK(wclk),
    .D(wdata[6]),
    .DE(_002_),
    .Q(\mem[11] [6])
  );
  sky130_fd_sc_hd__edfxtp_1 _249_ (
    .CLK(wclk),
    .D(wdata[7]),
    .DE(_002_),
    .Q(\mem[11] [7])
  );
  sky130_fd_sc_hd__edfxtp_1 _250_ (
    .CLK(wclk),
    .D(wdata[0]),
    .DE(_001_),
    .Q(\mem[10] [0])
  );
  sky130_fd_sc_hd__edfxtp_1 _251_ (
    .CLK(wclk),
    .D(wdata[1]),
    .DE(_001_),
    .Q(\mem[10] [1])
  );
  sky130_fd_sc_hd__edfxtp_1 _252_ (
    .CLK(wclk),
    .D(wdata[2]),
    .DE(_001_),
    .Q(\mem[10] [2])
  );
  sky130_fd_sc_hd__edfxtp_1 _253_ (
    .CLK(wclk),
    .D(wdata[3]),
    .DE(_001_),
    .Q(\mem[10] [3])
  );
  sky130_fd_sc_hd__edfxtp_1 _254_ (
    .CLK(wclk),
    .D(wdata[4]),
    .DE(_001_),
    .Q(\mem[10] [4])
  );
  sky130_fd_sc_hd__edfxtp_1 _255_ (
    .CLK(wclk),
    .D(wdata[5]),
    .DE(_001_),
    .Q(\mem[10] [5])
  );
  sky130_fd_sc_hd__edfxtp_1 _256_ (
    .CLK(wclk),
    .D(wdata[6]),
    .DE(_001_),
    .Q(\mem[10] [6])
  );
  sky130_fd_sc_hd__edfxtp_1 _257_ (
    .CLK(wclk),
    .D(wdata[7]),
    .DE(_001_),
    .Q(\mem[10] [7])
  );
  sky130_fd_sc_hd__edfxtp_1 _258_ (
    .CLK(wclk),
    .D(wdata[0]),
    .DE(_015_),
    .Q(\mem[9] [0])
  );
  sky130_fd_sc_hd__edfxtp_1 _259_ (
    .CLK(wclk),
    .D(wdata[1]),
    .DE(_015_),
    .Q(\mem[9] [1])
  );
  sky130_fd_sc_hd__edfxtp_1 _260_ (
    .CLK(wclk),
    .D(wdata[2]),
    .DE(_015_),
    .Q(\mem[9] [2])
  );
  sky130_fd_sc_hd__edfxtp_1 _261_ (
    .CLK(wclk),
    .D(wdata[3]),
    .DE(_015_),
    .Q(\mem[9] [3])
  );
  sky130_fd_sc_hd__edfxtp_1 _262_ (
    .CLK(wclk),
    .D(wdata[4]),
    .DE(_015_),
    .Q(\mem[9] [4])
  );
  sky130_fd_sc_hd__edfxtp_1 _263_ (
    .CLK(wclk),
    .D(wdata[5]),
    .DE(_015_),
    .Q(\mem[9] [5])
  );
  sky130_fd_sc_hd__edfxtp_1 _264_ (
    .CLK(wclk),
    .D(wdata[6]),
    .DE(_015_),
    .Q(\mem[9] [6])
  );
  sky130_fd_sc_hd__edfxtp_1 _265_ (
    .CLK(wclk),
    .D(wdata[7]),
    .DE(_015_),
    .Q(\mem[9] [7])
  );
  sky130_fd_sc_hd__edfxtp_1 _266_ (
    .CLK(wclk),
    .D(wdata[0]),
    .DE(_014_),
    .Q(\mem[8] [0])
  );
  sky130_fd_sc_hd__edfxtp_1 _267_ (
    .CLK(wclk),
    .D(wdata[1]),
    .DE(_014_),
    .Q(\mem[8] [1])
  );
  sky130_fd_sc_hd__edfxtp_1 _268_ (
    .CLK(wclk),
    .D(wdata[2]),
    .DE(_014_),
    .Q(\mem[8] [2])
  );
  sky130_fd_sc_hd__edfxtp_1 _269_ (
    .CLK(wclk),
    .D(wdata[3]),
    .DE(_014_),
    .Q(\mem[8] [3])
  );
  sky130_fd_sc_hd__edfxtp_1 _270_ (
    .CLK(wclk),
    .D(wdata[4]),
    .DE(_014_),
    .Q(\mem[8] [4])
  );
  sky130_fd_sc_hd__edfxtp_1 _271_ (
    .CLK(wclk),
    .D(wdata[5]),
    .DE(_014_),
    .Q(\mem[8] [5])
  );
  sky130_fd_sc_hd__edfxtp_1 _272_ (
    .CLK(wclk),
    .D(wdata[6]),
    .DE(_014_),
    .Q(\mem[8] [6])
  );
  sky130_fd_sc_hd__edfxtp_1 _273_ (
    .CLK(wclk),
    .D(wdata[7]),
    .DE(_014_),
    .Q(\mem[8] [7])
  );
  sky130_fd_sc_hd__edfxtp_1 _274_ (
    .CLK(wclk),
    .D(wdata[0]),
    .DE(_013_),
    .Q(\mem[7] [0])
  );
  sky130_fd_sc_hd__edfxtp_1 _275_ (
    .CLK(wclk),
    .D(wdata[1]),
    .DE(_013_),
    .Q(\mem[7] [1])
  );
  sky130_fd_sc_hd__edfxtp_1 _276_ (
    .CLK(wclk),
    .D(wdata[2]),
    .DE(_013_),
    .Q(\mem[7] [2])
  );
  sky130_fd_sc_hd__edfxtp_1 _277_ (
    .CLK(wclk),
    .D(wdata[3]),
    .DE(_013_),
    .Q(\mem[7] [3])
  );
  sky130_fd_sc_hd__edfxtp_1 _278_ (
    .CLK(wclk),
    .D(wdata[4]),
    .DE(_013_),
    .Q(\mem[7] [4])
  );
  sky130_fd_sc_hd__edfxtp_1 _279_ (
    .CLK(wclk),
    .D(wdata[5]),
    .DE(_013_),
    .Q(\mem[7] [5])
  );
  sky130_fd_sc_hd__edfxtp_1 _280_ (
    .CLK(wclk),
    .D(wdata[6]),
    .DE(_013_),
    .Q(\mem[7] [6])
  );
  sky130_fd_sc_hd__edfxtp_1 _281_ (
    .CLK(wclk),
    .D(wdata[7]),
    .DE(_013_),
    .Q(\mem[7] [7])
  );
  sky130_fd_sc_hd__edfxtp_1 _282_ (
    .CLK(wclk),
    .D(wdata[0]),
    .DE(_012_),
    .Q(\mem[6] [0])
  );
  sky130_fd_sc_hd__edfxtp_1 _283_ (
    .CLK(wclk),
    .D(wdata[1]),
    .DE(_012_),
    .Q(\mem[6] [1])
  );
  sky130_fd_sc_hd__edfxtp_1 _284_ (
    .CLK(wclk),
    .D(wdata[2]),
    .DE(_012_),
    .Q(\mem[6] [2])
  );
  sky130_fd_sc_hd__edfxtp_1 _285_ (
    .CLK(wclk),
    .D(wdata[3]),
    .DE(_012_),
    .Q(\mem[6] [3])
  );
  sky130_fd_sc_hd__edfxtp_1 _286_ (
    .CLK(wclk),
    .D(wdata[4]),
    .DE(_012_),
    .Q(\mem[6] [4])
  );
  sky130_fd_sc_hd__edfxtp_1 _287_ (
    .CLK(wclk),
    .D(wdata[5]),
    .DE(_012_),
    .Q(\mem[6] [5])
  );
  sky130_fd_sc_hd__edfxtp_1 _288_ (
    .CLK(wclk),
    .D(wdata[6]),
    .DE(_012_),
    .Q(\mem[6] [6])
  );
  sky130_fd_sc_hd__edfxtp_1 _289_ (
    .CLK(wclk),
    .D(wdata[7]),
    .DE(_012_),
    .Q(\mem[6] [7])
  );
  sky130_fd_sc_hd__edfxtp_1 _290_ (
    .CLK(wclk),
    .D(wdata[0]),
    .DE(_011_),
    .Q(\mem[5] [0])
  );
  sky130_fd_sc_hd__edfxtp_1 _291_ (
    .CLK(wclk),
    .D(wdata[1]),
    .DE(_011_),
    .Q(\mem[5] [1])
  );
  sky130_fd_sc_hd__edfxtp_1 _292_ (
    .CLK(wclk),
    .D(wdata[2]),
    .DE(_011_),
    .Q(\mem[5] [2])
  );
  sky130_fd_sc_hd__edfxtp_1 _293_ (
    .CLK(wclk),
    .D(wdata[3]),
    .DE(_011_),
    .Q(\mem[5] [3])
  );
  sky130_fd_sc_hd__edfxtp_1 _294_ (
    .CLK(wclk),
    .D(wdata[4]),
    .DE(_011_),
    .Q(\mem[5] [4])
  );
  sky130_fd_sc_hd__edfxtp_1 _295_ (
    .CLK(wclk),
    .D(wdata[5]),
    .DE(_011_),
    .Q(\mem[5] [5])
  );
  sky130_fd_sc_hd__edfxtp_1 _296_ (
    .CLK(wclk),
    .D(wdata[6]),
    .DE(_011_),
    .Q(\mem[5] [6])
  );
  sky130_fd_sc_hd__edfxtp_1 _297_ (
    .CLK(wclk),
    .D(wdata[7]),
    .DE(_011_),
    .Q(\mem[5] [7])
  );
  sky130_fd_sc_hd__edfxtp_1 _298_ (
    .CLK(wclk),
    .D(wdata[0]),
    .DE(_010_),
    .Q(\mem[4] [0])
  );
  sky130_fd_sc_hd__edfxtp_1 _299_ (
    .CLK(wclk),
    .D(wdata[1]),
    .DE(_010_),
    .Q(\mem[4] [1])
  );
  sky130_fd_sc_hd__edfxtp_1 _300_ (
    .CLK(wclk),
    .D(wdata[2]),
    .DE(_010_),
    .Q(\mem[4] [2])
  );
  sky130_fd_sc_hd__edfxtp_1 _301_ (
    .CLK(wclk),
    .D(wdata[3]),
    .DE(_010_),
    .Q(\mem[4] [3])
  );
  sky130_fd_sc_hd__edfxtp_1 _302_ (
    .CLK(wclk),
    .D(wdata[4]),
    .DE(_010_),
    .Q(\mem[4] [4])
  );
  sky130_fd_sc_hd__edfxtp_1 _303_ (
    .CLK(wclk),
    .D(wdata[5]),
    .DE(_010_),
    .Q(\mem[4] [5])
  );
  sky130_fd_sc_hd__edfxtp_1 _304_ (
    .CLK(wclk),
    .D(wdata[6]),
    .DE(_010_),
    .Q(\mem[4] [6])
  );
  sky130_fd_sc_hd__edfxtp_1 _305_ (
    .CLK(wclk),
    .D(wdata[7]),
    .DE(_010_),
    .Q(\mem[4] [7])
  );
  sky130_fd_sc_hd__edfxtp_1 _306_ (
    .CLK(wclk),
    .D(wdata[0]),
    .DE(_009_),
    .Q(\mem[3] [0])
  );
  sky130_fd_sc_hd__edfxtp_1 _307_ (
    .CLK(wclk),
    .D(wdata[1]),
    .DE(_009_),
    .Q(\mem[3] [1])
  );
  sky130_fd_sc_hd__edfxtp_1 _308_ (
    .CLK(wclk),
    .D(wdata[2]),
    .DE(_009_),
    .Q(\mem[3] [2])
  );
  sky130_fd_sc_hd__edfxtp_1 _309_ (
    .CLK(wclk),
    .D(wdata[3]),
    .DE(_009_),
    .Q(\mem[3] [3])
  );
  sky130_fd_sc_hd__edfxtp_1 _310_ (
    .CLK(wclk),
    .D(wdata[4]),
    .DE(_009_),
    .Q(\mem[3] [4])
  );
  sky130_fd_sc_hd__edfxtp_1 _311_ (
    .CLK(wclk),
    .D(wdata[5]),
    .DE(_009_),
    .Q(\mem[3] [5])
  );
  sky130_fd_sc_hd__edfxtp_1 _312_ (
    .CLK(wclk),
    .D(wdata[6]),
    .DE(_009_),
    .Q(\mem[3] [6])
  );
  sky130_fd_sc_hd__edfxtp_1 _313_ (
    .CLK(wclk),
    .D(wdata[7]),
    .DE(_009_),
    .Q(\mem[3] [7])
  );
  sky130_fd_sc_hd__edfxtp_1 _314_ (
    .CLK(wclk),
    .D(wdata[0]),
    .DE(_008_),
    .Q(\mem[2] [0])
  );
  sky130_fd_sc_hd__edfxtp_1 _315_ (
    .CLK(wclk),
    .D(wdata[1]),
    .DE(_008_),
    .Q(\mem[2] [1])
  );
  sky130_fd_sc_hd__edfxtp_1 _316_ (
    .CLK(wclk),
    .D(wdata[2]),
    .DE(_008_),
    .Q(\mem[2] [2])
  );
  sky130_fd_sc_hd__edfxtp_1 _317_ (
    .CLK(wclk),
    .D(wdata[3]),
    .DE(_008_),
    .Q(\mem[2] [3])
  );
  sky130_fd_sc_hd__edfxtp_1 _318_ (
    .CLK(wclk),
    .D(wdata[4]),
    .DE(_008_),
    .Q(\mem[2] [4])
  );
  sky130_fd_sc_hd__edfxtp_1 _319_ (
    .CLK(wclk),
    .D(wdata[5]),
    .DE(_008_),
    .Q(\mem[2] [5])
  );
  sky130_fd_sc_hd__edfxtp_1 _320_ (
    .CLK(wclk),
    .D(wdata[6]),
    .DE(_008_),
    .Q(\mem[2] [6])
  );
  sky130_fd_sc_hd__edfxtp_1 _321_ (
    .CLK(wclk),
    .D(wdata[7]),
    .DE(_008_),
    .Q(\mem[2] [7])
  );
  sky130_fd_sc_hd__edfxtp_1 _322_ (
    .CLK(wclk),
    .D(wdata[0]),
    .DE(_007_),
    .Q(\mem[1] [0])
  );
  sky130_fd_sc_hd__edfxtp_1 _323_ (
    .CLK(wclk),
    .D(wdata[1]),
    .DE(_007_),
    .Q(\mem[1] [1])
  );
  sky130_fd_sc_hd__edfxtp_1 _324_ (
    .CLK(wclk),
    .D(wdata[2]),
    .DE(_007_),
    .Q(\mem[1] [2])
  );
  sky130_fd_sc_hd__edfxtp_1 _325_ (
    .CLK(wclk),
    .D(wdata[3]),
    .DE(_007_),
    .Q(\mem[1] [3])
  );
  sky130_fd_sc_hd__edfxtp_1 _326_ (
    .CLK(wclk),
    .D(wdata[4]),
    .DE(_007_),
    .Q(\mem[1] [4])
  );
  sky130_fd_sc_hd__edfxtp_1 _327_ (
    .CLK(wclk),
    .D(wdata[5]),
    .DE(_007_),
    .Q(\mem[1] [5])
  );
  sky130_fd_sc_hd__edfxtp_1 _328_ (
    .CLK(wclk),
    .D(wdata[6]),
    .DE(_007_),
    .Q(\mem[1] [6])
  );
  sky130_fd_sc_hd__edfxtp_1 _329_ (
    .CLK(wclk),
    .D(wdata[7]),
    .DE(_007_),
    .Q(\mem[1] [7])
  );
  sky130_fd_sc_hd__edfxtp_1 _330_ (
    .CLK(wclk),
    .D(wdata[0]),
    .DE(_000_),
    .Q(\mem[0] [0])
  );
  sky130_fd_sc_hd__edfxtp_1 _331_ (
    .CLK(wclk),
    .D(wdata[1]),
    .DE(_000_),
    .Q(\mem[0] [1])
  );
  sky130_fd_sc_hd__edfxtp_1 _332_ (
    .CLK(wclk),
    .D(wdata[2]),
    .DE(_000_),
    .Q(\mem[0] [2])
  );
  sky130_fd_sc_hd__edfxtp_1 _333_ (
    .CLK(wclk),
    .D(wdata[3]),
    .DE(_000_),
    .Q(\mem[0] [3])
  );
  sky130_fd_sc_hd__edfxtp_1 _334_ (
    .CLK(wclk),
    .D(wdata[4]),
    .DE(_000_),
    .Q(\mem[0] [4])
  );
  sky130_fd_sc_hd__edfxtp_1 _335_ (
    .CLK(wclk),
    .D(wdata[5]),
    .DE(_000_),
    .Q(\mem[0] [5])
  );
  sky130_fd_sc_hd__edfxtp_1 _336_ (
    .CLK(wclk),
    .D(wdata[6]),
    .DE(_000_),
    .Q(\mem[0] [6])
  );
  sky130_fd_sc_hd__edfxtp_1 _337_ (
    .CLK(wclk),
    .D(wdata[7]),
    .DE(_000_),
    .Q(\mem[0] [7])
  );
  (* src = "afifo.v:81.1-85.24" *)
  sky130_fd_sc_hd__dfstp_2 _338_ (
    .CLK(rclk),
    .D(rempty_next),
    .Q(rempty),
    .SET_B(rrstn)
  );
  (* src = "afifo.v:72.2-76.45" *)
  sky130_fd_sc_hd__dfrtp_1 _339_ (
    .CLK(rclk),
    .D(rgraynext[0]),
    .Q(rgray[0]),
    .RESET_B(rrstn)
  );
  (* src = "afifo.v:72.2-76.45" *)
  sky130_fd_sc_hd__dfrtp_1 _340_ (
    .CLK(rclk),
    .D(rgraynext[1]),
    .Q(rgray[1]),
    .RESET_B(rrstn)
  );
  (* src = "afifo.v:72.2-76.45" *)
  sky130_fd_sc_hd__dfrtp_1 _341_ (
    .CLK(rclk),
    .D(rgraynext[2]),
    .Q(rgray[2]),
    .RESET_B(rrstn)
  );
  (* src = "afifo.v:72.2-76.45" *)
  sky130_fd_sc_hd__dfrtp_1 _342_ (
    .CLK(rclk),
    .D(rgraynext[3]),
    .Q(rgray[3]),
    .RESET_B(rrstn)
  );
  (* src = "afifo.v:72.2-76.45" *)
  sky130_fd_sc_hd__dfrtp_1 _343_ (
    .CLK(rclk),
    .D(rbinnext[0]),
    .Q(rbin[0]),
    .RESET_B(rrstn)
  );
  (* src = "afifo.v:72.2-76.45" *)
  sky130_fd_sc_hd__dfrtp_1 _344_ (
    .CLK(rclk),
    .D(rbinnext[1]),
    .Q(rbin[1]),
    .RESET_B(rrstn)
  );
  (* src = "afifo.v:72.2-76.45" *)
  sky130_fd_sc_hd__dfrtp_1 _345_ (
    .CLK(rclk),
    .D(rbinnext[2]),
    .Q(rbin[2]),
    .RESET_B(rrstn)
  );
  (* src = "afifo.v:72.2-76.45" *)
  sky130_fd_sc_hd__dfrtp_1 _346_ (
    .CLK(rclk),
    .D(rbinnext[3]),
    .Q(rbin[3]),
    .RESET_B(rrstn)
  );
  (* src = "afifo.v:72.2-76.45" *)
  sky130_fd_sc_hd__dfrtp_1 _347_ (
    .CLK(rclk),
    .D(rbinnext[4]),
    .Q(rbin[4]),
    .RESET_B(rrstn)
  );
  (* src = "afifo.v:61.1-65.50" *)
  sky130_fd_sc_hd__dfrtp_1 _348_ (
    .CLK(rclk),
    .D(rq1_wgray[0]),
    .Q(rq2_wgray[0]),
    .RESET_B(rrstn)
  );
  (* src = "afifo.v:61.1-65.50" *)
  sky130_fd_sc_hd__dfrtp_1 _349_ (
    .CLK(rclk),
    .D(rq1_wgray[1]),
    .Q(rq2_wgray[1]),
    .RESET_B(rrstn)
  );
  (* src = "afifo.v:61.1-65.50" *)
  sky130_fd_sc_hd__dfrtp_1 _350_ (
    .CLK(rclk),
    .D(rq1_wgray[2]),
    .Q(rq2_wgray[2]),
    .RESET_B(rrstn)
  );
  (* src = "afifo.v:61.1-65.50" *)
  sky130_fd_sc_hd__dfrtp_1 _351_ (
    .CLK(rclk),
    .D(rq1_wgray[3]),
    .Q(rq2_wgray[3]),
    .RESET_B(rrstn)
  );
  (* src = "afifo.v:61.1-65.50" *)
  sky130_fd_sc_hd__dfrtp_1 _352_ (
    .CLK(rclk),
    .D(rq1_wgray[4]),
    .Q(rq2_wgray[4]),
    .RESET_B(rrstn)
  );
  (* src = "afifo.v:61.1-65.50" *)
  sky130_fd_sc_hd__dfrtp_1 _353_ (
    .CLK(rclk),
    .D(wgray[0]),
    .Q(rq1_wgray[0]),
    .RESET_B(rrstn)
  );
  (* src = "afifo.v:61.1-65.50" *)
  sky130_fd_sc_hd__dfrtp_1 _354_ (
    .CLK(rclk),
    .D(wgray[1]),
    .Q(rq1_wgray[1]),
    .RESET_B(rrstn)
  );
  (* src = "afifo.v:61.1-65.50" *)
  sky130_fd_sc_hd__dfrtp_1 _355_ (
    .CLK(rclk),
    .D(wgray[2]),
    .Q(rq1_wgray[2]),
    .RESET_B(rrstn)
  );
  (* src = "afifo.v:61.1-65.50" *)
  sky130_fd_sc_hd__dfrtp_1 _356_ (
    .CLK(rclk),
    .D(wgray[3]),
    .Q(rq1_wgray[3]),
    .RESET_B(rrstn)
  );
  (* src = "afifo.v:61.1-65.50" *)
  sky130_fd_sc_hd__dfrtp_1 _357_ (
    .CLK(rclk),
    .D(wgray[4]),
    .Q(rq1_wgray[4]),
    .RESET_B(rrstn)
  );
  (* src = "afifo.v:47.9-53.18" *)
  sky130_fd_sc_hd__dfrtp_1 _358_ (
    .CLK(wclk),
    .D(wfull_next),
    .Q(wfull),
    .RESET_B(wrstn)
  );
  (* src = "afifo.v:38.7-44.12" *)
  sky130_fd_sc_hd__dfrtp_1 _359_ (
    .CLK(wclk),
    .D(wbinnext[0]),
    .Q(wbin[0]),
    .RESET_B(wrstn)
  );
  (* src = "afifo.v:38.7-44.12" *)
  sky130_fd_sc_hd__dfrtp_1 _360_ (
    .CLK(wclk),
    .D(wbinnext[1]),
    .Q(wbin[1]),
    .RESET_B(wrstn)
  );
  (* src = "afifo.v:38.7-44.12" *)
  sky130_fd_sc_hd__dfrtp_1 _361_ (
    .CLK(wclk),
    .D(wbinnext[2]),
    .Q(wbin[2]),
    .RESET_B(wrstn)
  );
  (* src = "afifo.v:38.7-44.12" *)
  sky130_fd_sc_hd__dfrtp_1 _362_ (
    .CLK(wclk),
    .D(wbinnext[3]),
    .Q(wbin[3]),
    .RESET_B(wrstn)
  );
  (* src = "afifo.v:38.7-44.12" *)
  sky130_fd_sc_hd__dfrtp_1 _363_ (
    .CLK(wclk),
    .D(wgraynext[0]),
    .Q(wgray[0]),
    .RESET_B(wrstn)
  );
  (* src = "afifo.v:38.7-44.12" *)
  sky130_fd_sc_hd__dfrtp_1 _364_ (
    .CLK(wclk),
    .D(wgraynext[1]),
    .Q(wgray[1]),
    .RESET_B(wrstn)
  );
  (* src = "afifo.v:38.7-44.12" *)
  sky130_fd_sc_hd__dfrtp_1 _365_ (
    .CLK(wclk),
    .D(wgraynext[2]),
    .Q(wgray[2]),
    .RESET_B(wrstn)
  );
  (* src = "afifo.v:38.7-44.12" *)
  sky130_fd_sc_hd__dfrtp_1 _366_ (
    .CLK(wclk),
    .D(wgraynext[3]),
    .Q(wgray[3]),
    .RESET_B(wrstn)
  );
  (* src = "afifo.v:38.7-44.12" *)
  sky130_fd_sc_hd__dfrtp_1 _367_ (
    .CLK(wclk),
    .D(wbinnext[4]),
    .Q(wgray[4]),
    .RESET_B(wrstn)
  );
  (* src = "afifo.v:25.7-31.12" *)
  sky130_fd_sc_hd__dfrtp_1 _368_ (
    .CLK(wclk),
    .D(wq1_rgray[0]),
    .Q(wq2_rgray[0]),
    .RESET_B(wrstn)
  );
  (* src = "afifo.v:25.7-31.12" *)
  sky130_fd_sc_hd__dfrtp_1 _369_ (
    .CLK(wclk),
    .D(wq1_rgray[1]),
    .Q(wq2_rgray[1]),
    .RESET_B(wrstn)
  );
  (* src = "afifo.v:25.7-31.12" *)
  sky130_fd_sc_hd__dfrtp_1 _370_ (
    .CLK(wclk),
    .D(wq1_rgray[2]),
    .Q(wq2_rgray[2]),
    .RESET_B(wrstn)
  );
  (* src = "afifo.v:25.7-31.12" *)
  sky130_fd_sc_hd__dfrtp_1 _371_ (
    .CLK(wclk),
    .D(wq1_rgray[3]),
    .Q(wq2_rgray[3]),
    .RESET_B(wrstn)
  );
  (* src = "afifo.v:25.7-31.12" *)
  sky130_fd_sc_hd__dfrtp_1 _372_ (
    .CLK(wclk),
    .D(wq1_rgray[4]),
    .Q(wq2_rgray[4]),
    .RESET_B(wrstn)
  );
  (* src = "afifo.v:25.7-31.12" *)
  sky130_fd_sc_hd__dfrtp_1 _373_ (
    .CLK(wclk),
    .D(rgray[0]),
    .Q(wq1_rgray[0]),
    .RESET_B(wrstn)
  );
  (* src = "afifo.v:25.7-31.12" *)
  sky130_fd_sc_hd__dfrtp_1 _374_ (
    .CLK(wclk),
    .D(rgray[1]),
    .Q(wq1_rgray[1]),
    .RESET_B(wrstn)
  );
  (* src = "afifo.v:25.7-31.12" *)
  sky130_fd_sc_hd__dfrtp_1 _375_ (
    .CLK(wclk),
    .D(rgray[2]),
    .Q(wq1_rgray[2]),
    .RESET_B(wrstn)
  );
  (* src = "afifo.v:25.7-31.12" *)
  sky130_fd_sc_hd__dfrtp_1 _376_ (
    .CLK(wclk),
    .D(rgray[3]),
    .Q(wq1_rgray[3]),
    .RESET_B(wrstn)
  );
  (* src = "afifo.v:25.7-31.12" *)
  sky130_fd_sc_hd__dfrtp_1 _377_ (
    .CLK(wclk),
    .D(rbin[4]),
    .Q(wq1_rgray[4]),
    .RESET_B(wrstn)
  );
  assign rgraynext[4] = rbinnext[4];
  assign wgraynext[4] = wbinnext[4];
  assign rgray[4] = rbin[4];
  assign wbin[4] = wgray[4];
  assign raddr = rbin[3:0];
  assign waddr = wbin[3:0];
endmodule
